# [START runtime]
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT MoviesForRent.wsgi

beta_settings:
    cloud_sql_instances: rent-a-movie-231721:us-central1:movies-beta

runtime_config:
  python_version: 3
# [END runtime]
